let csrf='', usersPage=0, selected=null, detailPage=0;
const $=id=>document.getElementById(id);
const bytes=n=>n>=1073741824?(n/1073741824).toFixed(2)+' GB':(n/1048576).toFixed(1)+' MB';
const date=s=>s?new Date(s).toLocaleString():'â€”';
function element(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function button(text,fn,cls){const b=element('button',text,cls);b.onclick=async()=>{b.disabled=true;try{await fn();}catch(e){$('notice').textContent=e.message;}finally{b.disabled=false;}};return b;}
async function api(url,method='GET'){const r=await fetch(url,{method,headers:method==='DELETE'?{'X-CSRF-Token':csrf}:{}});if(!r.ok)throw Error((await r.text())||'Request failed');return r.json();}
function disk(d){$('disk').textContent=`${bytes(d.bytes)} in ${d.files} downloaded files Â· ${bytes(d.free)} free on server`;}
async function overview(){const d=await api('/api/overview');csrf=d.csrf;disk(d.disk);traffic(d);$('stats').replaceChildren();for(const [label,value]of [['Users',d.stats.users],['Video requests',d.stats.requests],['Success rate',d.stats.success_rate===null?'â€”':d.stats.success_rate+'%'],['Completed',d.stats.completed],['Failed',d.stats.failed],['Pending',d.stats.pending],['GIF requests',d.stats.gifs],['Starts',d.stats.starts]]){const c=element('div',undefined,'stat');c.append(element('span',label),element('strong',String(value)));$('stats').append(c);}}
function pages(container,page,total,size,change){container.replaceChildren();const prev=button('Previous',()=>change(page-1)),next=button('Next',()=>change(page+1));prev.disabled=page===0;next.disabled=(page+1)*size>=total;container.append(prev,element('span',`${page+1} / ${Math.max(1,Math.ceil(total/size))}`),next);}
async function users(){const d=await api(`/api/users?page=${usersPage}&search=${encodeURIComponent($('search').value)}`);$('users').replaceChildren();for(const u of d.items){const b=button([u.first_name,u.last_name].filter(Boolean).join(' ')||String(u.user_id),async()=>{selected=u.user_id;detailPage=0;await Promise.all([detail(),users()]);},'user'+(u.user_id===selected?' active':''));b.append(element('small',`${u.username?'@'+u.username+' Â· ':''}${u.media_requests} requests Â· ${u.user_id}`));$('users').append(b);}if(!d.items.length)$('users').append(element('p','No users found.','muted'));pages($('users-pages'),usersPage,d.total,50,async p=>{usersPage=p;await users();});}
async function detail(){if(selected===null)return;const d=await api(`/api/users/${selected}?page=${detailPage}`);const root=$('detail');root.replaceChildren();root.append(element('h2',[d.user.first_name,d.user.last_name].filter(Boolean).join(' ')||String(selected)),element('p',`${d.user.username?'@'+d.user.username+' Â· ':''}ID ${selected}`,'muted'),element('p',`First seen ${date(d.user.first_seen_at)} Â· Last seen ${date(d.user.last_seen_at)}`,'muted'),element('h3','Videos & outputs','section-title'));
const q=d.quota;root.append(element('p',`Remaining requests: ${q.remaining} / ${q.limit} · Resets ${q.reset_at} (Tehran)`));
for(const j of d.jobs){const card=element('article',undefined,'job');const row=element('div',undefined,'row');row.append(element('h3',`Request #${j.id}`),element('span',j.status,'badge '+j.status));card.append(row,element('p',`${date(j.created_at)} Â· ${j.source_kind}`,'muted'));if(j.prompt_text)card.append(element('p',j.prompt_text,'text'));if(j.trim_input_text)card.append(element('p','Trim input: '+j.trim_input_text,'text'));if(j.trim_start!==null)card.append(element('small',`Selected range: ${j.trim_start}s â†’ ${j.trim_end}s`));for(const [kind,available] of Object.entries(j.media)){if(!available)continue;const box=element('div',undefined,'media'),actions=element('div',undefined,'actions'),url=`/media/${j.id}/${kind}`;box.append(element('strong',{'source':'Original upload','video_note':'Video message','animation':'GIF'}[kind]));actions.append(button('View',async()=>{if(box.querySelector('video,img'))return;const v=element(kind==='source'&&j.source_mime_type==='image/gif'?'img':'video');if(v.tagName==='VIDEO'){v.controls=true;v.preload='metadata';v.playsInline=true;}v.src=url;v.onerror=()=>{$('notice').textContent='Media could not be loaded. Try Download or refresh.';};box.append(v);}));const link=element('a','Download','download');link.href=url+'?download=1';actions.append(link,button('Delete server copy',async()=>{if(!confirm('Delete this downloaded server copy? Telegram references and history will remain.'))return;const r=await api(url,'DELETE');disk(r.disk);const v=box.querySelector('video,img');if(v){v.removeAttribute('src');if(v.load)v.load();v.remove();}$('notice').textContent=`Freed ${bytes(r.removed_bytes)}. You can download this media again.`;},'danger'));box.append(actions);card.append(box);}root.append(card);}
if(!d.jobs.length)root.append(element('p','No video requests on this page.','muted'));root.append(element('h3','Prompt history','section-title'));for(const p of d.prompts){const box=element('article',undefined,'prompt');box.append(element('small',`${date(p.created_at)} Â· ${p.kind}`),element('p',p.text,'text'));root.append(box);}if(!d.prompts.length)root.append(element('p','No saved prompts on this page.','muted'));const nav=element('nav');root.append(nav);pages(nav,detailPage,Math.max(d.jobs_total,d.prompts_total),25,async p=>{detailPage=p;await detail();});}
$('refresh').onclick=()=>refresh();$('clear').onclick=async()=>{if(!confirm('Clear all downloaded dashboard media and inspection exports? User history, Telegram media references and active bot processing files will remain.'))return;try{const d=await api('/api/cache','DELETE');disk(d.disk);$('notice').textContent=`Freed ${bytes(d.removed_bytes)}.`;await detail();}catch(e){$('notice').textContent=e.message;}};
let timer;$('search').oninput=()=>{clearTimeout(timer);timer=setTimeout(()=>{usersPage=0;users().catch(e=>$('notice').textContent=e.message);},250);};
async function refresh(){try{$('notice').textContent='';await overview();await users();await detail();}catch(e){$('notice').textContent=e.message;}}refresh();

function traffic(d){const rows=new Map(d.traffic.map(r=>[r.route,r]));const total=d.traffic.reduce((n,r)=>n+r.uploaded+r.downloaded,0);$('traffic-status').textContent=d.cloudflare_enabled?'Cloudflare first, proxy fallback':'Cloudflare is not configured; proxy/direct routing is active.';$('traffic').replaceChildren();for(const [key,label] of [['cloudflare','Cloudflare'],['proxy','Your proxy'],['direct','Direct']]){const r=rows.get(key)||{uploaded:0,downloaded:0,requests:0};if(key==='direct'&&!rows.has(key))continue;const n=r.uploaded+r.downloaded;const box=element('p',`${label}: ${bytes(n)} (${total?(100*n/total).toFixed(1):'0'}%) · sent ${bytes(r.uploaded)} · received ${bytes(r.downloaded)} · ${r.requests} requests`);$('traffic').append(box);}}
